/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.*;  
import java.awt.event.*;
import javax.swing.*;
import mainCode.*;
import mainCode.pictureClasses.*;
import util.*;
import java.util.Observer;
import java.util.Observable;

/**
 *
 * @author kaan.uguralp-ug
 */
public class CountryInfo extends JPanel implements Observer {
   
   // Variables declaration - do not modify 
   Game game;
   ResizablePicture countryPicture;                  
   private JLabel accomodationFee;
   private JLabel citizenshipFee;
   private JLabel countryName;
   private JLabel countryPic;
   private JButton getCitizenship;
   private JLabel income;
   private JButton payAccomodationFee;
   // End of variables declaration
   
   /**
    * Creates new form CountryInfo
    */
   public CountryInfo( Game game ) {
      this.game = game;
      
      // Add Observer
      for ( int n = 0; n < Route.COUNTRY_NUMBER; n++ )
      {
         Route.COUNTRIES_ON_ROUTE.get( n ).addObserver( this );
      }
      
      initComponents();
      handleActionListeners();
      
      setVisible( false );
   }
   
   // Listener Classes 
   
   // Pay Accomodation Fee Button Listener 
   public class PayAccomodationFeeBtnListener implements ActionListener
   { 
      @Override
      public void actionPerformed( ActionEvent evt )
      {
         game.payAccomodationFee();  
         
         setVisible( false );
      }
   }
   
   // Get Citizenship Button Listener 
   public class GetCitizenshipBtnListener implements ActionListener
   { 
      @Override
      public void actionPerformed( ActionEvent evt )
      {
         game.getCitizenship();
         
         setVisible( false );
      }
   }
   
   public void handleActionListeners()
   {
      payAccomodationFee.addActionListener( new PayAccomodationFeeBtnListener() );
      getCitizenship.addActionListener( new GetCitizenshipBtnListener() );
   }
   
   public void update( Observable obs, Object obj )
   {
      Country c = (Country)obs;
      
      countryName.setText( c.getName() );
      accomodationFee.setText( "Accomodation Fee: " + c.getAccomodationFee()  );
      citizenshipFee.setText( "Citizenship Fee: " + 30 );
      income.setText( "Income: " + c.getTax() );
      countryPicture.setPicture( c.getPicture() );
      
//      if ( countries.size() < p.getNumberOfCountries() )
//      {
//         createCountryPanel( p.getLastCountry() );
//      }
      
      setVisible( true );
   }   
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
      private void initComponents() {
      
      countryPicture = new CountryPicture();
      countryPic = new JLabel();
      countryPic.add( countryPicture );
      
      countryName = new JLabel();
      accomodationFee = new JLabel();
      citizenshipFee = new JLabel();
      income = new JLabel();
      payAccomodationFee = new JButton();
      getCitizenship = new JButton();
      
      setBackground(new java.awt.Color(102, 255, 255));
      
      countryName.setFont(new java.awt.Font("Gisha", 1, 24)); // NOI18N
      countryName.setForeground(new java.awt.Color(0, 102, 102));
      countryName.setHorizontalAlignment(SwingConstants.CENTER);
      countryName.setText("countryName");
      countryName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      countryName.setDebugGraphicsOptions(DebugGraphics.NONE_OPTION);
      
      countryPic.setText("countryPicture");
      
      accomodationFee.setFont(new java.awt.Font("Gisha", 0, 24)); // NOI18N
      accomodationFee.setForeground(new java.awt.Color(0, 102, 102));
      accomodationFee.setText("Acc fee");
      
      citizenshipFee.setFont(new java.awt.Font("Gisha", 0, 24)); // NOI18N
      citizenshipFee.setForeground(new java.awt.Color(0, 102, 102));
      citizenshipFee.setText("citizenshipFee");
      
      income.setFont(new java.awt.Font("Gisha", 0, 24)); // NOI18N
      income.setForeground(new java.awt.Color(0, 102, 102));
      income.setText("income");
      
      payAccomodationFee.setFont(new java.awt.Font("Gisha", 0, 18)); // NOI18N
      payAccomodationFee.setForeground(new java.awt.Color(0, 0, 102));
      payAccomodationFee.setText("Pay Accomodation Fee");
      payAccomodationFee.setBorder(null);
      payAccomodationFee.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
      
      getCitizenship.setFont(new java.awt.Font("Gisha", 0, 18)); // NOI18N
      getCitizenship.setForeground(new java.awt.Color(0, 0, 102));
      getCitizenship.setText("Get Citizenship");
      getCitizenship.setBorder(null);
      getCitizenship.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
      
      GroupLayout layout = new GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
                                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                             .addGroup(layout.createSequentialGroup()
                                                                          .addContainerGap()
                                                                          .addComponent(payAccomodationFee, GroupLayout.PREFERRED_SIZE, 233, GroupLayout.PREFERRED_SIZE)
                                                                          .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                          .addComponent(getCitizenship, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE))
                                                             .addGroup(layout.createSequentialGroup()
                                                                          .addGap(95, 95, 95)
                                                                          .addComponent(countryPic, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE))
                                                             .addGroup(layout.createSequentialGroup()
                                                                          .addGap(58, 58, 58)
                                                                          .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                                                       .addComponent(countryName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                       .addComponent(accomodationFee, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                       .addComponent(citizenshipFee, GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                                                                       .addComponent(income, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                               );
      layout.setVerticalGroup(
                              layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                 .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                              .addGap(6, 6, 6)
                                              .addComponent(countryPic, GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                              .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                              .addComponent(countryName, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                                              .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                              .addComponent(accomodationFee, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                                              .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                              .addComponent(citizenshipFee)
                                              .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                              .addComponent(income)
                                              .addGap(30, 30, 30)
                                              .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                           .addComponent(payAccomodationFee, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
                                                           .addComponent(getCitizenship, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE))
                                              .addGap(31, 31, 31))
                             );
   }// </editor-fold>                                      
}
