/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import mainCode.pictureClasses.Avatar;
import util.ResizablePicture;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JPanel;
import mainCode.Player;

/**
 * LT creates new form LeadershipTablePanel
 * @author Emin Adem Buran
 * @version 12.05.2019
 */
public class LT extends JPanel implements Observer {
   
   //properties
  
   //constructors
   public LT( Player p ) 
   {
      p.addObserver( this );
      initComponents( p.getPlayerNo() + 1, p.getName(), p.getNumberOfCountries(), p.getMoney(), p.getAvatar() );
   }
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
      private void initComponents( int num, String names, int numOfCountries, int moneys, Avatar avatar ) {
      name = new javax.swing.JLabel();
      noOfCountries = new javax.swing.JLabel();
      money = new javax.swing.JLabel();
      number = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      avatarLabel = new javax.swing.JLabel();
      
      avatarLabel.add( new Avatar( avatar.getAvatarName() ) );
      
      setBackground(new java.awt.Color(102, 255, 255));
      setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
      
      name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      name.setForeground(new java.awt.Color(0, 0, 153));
      name.setText( "Nickname: " + names);
      
      noOfCountries.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      noOfCountries.setForeground(new java.awt.Color(0, 0, 153));
      noOfCountries.setText( "Number of Countries: " + numOfCountries );
      
      money.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      money.setForeground(new java.awt.Color(0, 153, 0));
      money.setText( "Money: " + moneys + "" );
      
      number.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      number.setForeground(new java.awt.Color(0, 0, 255));
      number.setText(num + ".");
      
      jLabel2.setOpaque(true);
      
      jLabel3.setOpaque(true);
      
      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(noOfCountries, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24))
                               );
      layout.setVerticalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addGroup(layout.createSequentialGroup()
                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                           .addGroup(layout.createSequentialGroup()
                                                                        .addContainerGap()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                     .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                     .addGroup(layout.createSequentialGroup()
                                                                                                  .addGap(14, 14, 14)
                                                                                                  .addComponent(name))
                                                                                     .addGroup(layout.createSequentialGroup()
                                                                                                  .addGap(13, 13, 13)
                                                                                                  .addComponent(number))))
                                                           .addGroup(layout.createSequentialGroup()
                                                                        .addGap(24, 24, 24)
                                                                        .addComponent(noOfCountries)))
                                              .addGap(0, 11, Short.MAX_VALUE))
                                 .addGroup(layout.createSequentialGroup()
                                              .addGap(24, 24, 24)
                                              .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                             );
   }// </editor-fold>                        
   
   
   // Variables declaration - do not modify                     
   private javax.swing.JLabel avatarLabel;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel money;
   private javax.swing.JLabel name;
   private javax.swing.JLabel noOfCountries;
   private javax.swing.JLabel number;
   // End of variables declaration   
   
   // updating the LT 
   public void update( Observable obs, Object obj )
   {
      Player p = (Player)obs;
      
      money.setText( p.getMoney() + "" );
      noOfCountries.setText( p.getNumberOfCountries() + "" );
   }     
   
   // updating Rank 
   public void setRank( int n )
   {
      number.setText( n + "" );
   }
}
