/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;
import java.util.ArrayList;
import mainCode.*;
import mainCode.pictureClasses.Avatar;
import util.GameFileReader;

/**
 *
 * @author kaan.uguralp-ug
 */
public class PlayerMenu extends javax.swing.JPanel {
   
   int numberOfPlayers;
   ArrayList<String> listedCountries; // countries that are listed as in the game ( the usage explained above the method )
   String[] alphabeticalCountries; // we need alphabetical list of countries in scroll panes
   Avatar[] avatars;
   Application app; 
   
   /**
    * Creates new form PlayerMenu
    */
   public PlayerMenu( Application app ) {
      
      this.app = app;
      
      alphabeticalCountries = GameFileReader.getAlphabeticalCountriesArray(); // will be needed in country lists
      avatars = GameFileReader.getAvatarsArray(); // will be needed in avatar lists   
      listedCountries = GameFileReader.getListedCountries(); // will be needed when the game is starting
      
      initComponents();
      
      p1Panel.setVisible(false);
      p2Panel.setVisible(false);
      p3Panel.setVisible(false);
      p4Panel.setVisible(false);
      
      setSize( app.getSize() );   // "super" JFrame sets initial size
      setVisible( false );    // "super" JFrame shows
   }
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
      private void initComponents() {
      
      jLabel1 = new javax.swing.JLabel();
      p1Panel = new javax.swing.JPanel();
      p1Name = new javax.swing.JTextField();
      p1Country = new javax.swing.JScrollPane();
      countryList1 = new javax.swing.JList();
      p1Avatar = new javax.swing.JScrollPane();
      avatarList1 = new javax.swing.JList();
      p2Panel = new javax.swing.JPanel();
      p2Name = new javax.swing.JTextField();
      p2Country = new javax.swing.JScrollPane();
      countryList2 = new javax.swing.JList();
      p2Avatar = new javax.swing.JScrollPane();
      avatarList2 = new javax.swing.JList();
      p3Panel = new javax.swing.JPanel();
      p3Name = new javax.swing.JTextField();
      p3Country = new javax.swing.JScrollPane();
      countryList3 = new javax.swing.JList();
      p3Avatar = new javax.swing.JScrollPane();
      avatarList3 = new javax.swing.JList();
      p4Panel = new javax.swing.JPanel();
      p4Name = new javax.swing.JTextField();
      p4Country = new javax.swing.JScrollPane();
      countryList4 = new javax.swing.JList();
      p4Avatar = new javax.swing.JScrollPane();
      avatarList4 = new javax.swing.JList();
      oneCheck = new javax.swing.JRadioButton();
      twoCheck = new javax.swing.JRadioButton();
      threeCheck = new javax.swing.JRadioButton();
      fourCheck = new javax.swing.JRadioButton();
      back = new javax.swing.JButton();
      start = new javax.swing.JButton();
      
      setBackground(new java.awt.Color(102, 255, 255));
      
      jLabel1.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
      jLabel1.setText("Choose Player Number");
      
      p1Panel.setBackground(new java.awt.Color(153, 255, 153));
      
      p1Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      p1Name.setForeground(new java.awt.Color(0, 102, 0));
      p1Name.setText("Enter Nickname");
      
      p1Country.setBackground(new java.awt.Color(204, 255, 204));
      p1Country.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      p1Country.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      
      countryList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      countryList1.setModel(new javax.swing.AbstractListModel() {
         String[] strings = alphabeticalCountries;
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      p1Country.setViewportView(countryList1);
      
      p1Avatar.setBackground(new java.awt.Color(204, 255, 204));
      p1Avatar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      
      avatarList1.setModel(new javax.swing.AbstractListModel() {
         Avatar[] strings = avatars;
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      p1Avatar.setViewportView(avatarList1);
      avatarList1.setVisibleRowCount( 3 );
      avatarList1.setLayoutOrientation( javax.swing.JList.HORIZONTAL_WRAP );
      
      javax.swing.GroupLayout p1PanelLayout = new javax.swing.GroupLayout(p1Panel);
      p1Panel.setLayout(p1PanelLayout);
      p1PanelLayout.setHorizontalGroup(
                                       p1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(p1PanelLayout.createSequentialGroup()
                                                       .addContainerGap()
                                                       .addComponent(p1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addGap(58, 58, 58)
                                                       .addComponent(p1Country, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                                       .addGap(18, 18, 18)
                                                       .addComponent(p1Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addContainerGap())
                                      );
      p1PanelLayout.setVerticalGroup(
                                     p1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(p1PanelLayout.createSequentialGroup()
                                                     .addGap(69, 69, 69)
                                                     .addComponent(p1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                     .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1PanelLayout.createSequentialGroup()
                                                     .addContainerGap()
                                                     .addGroup(p1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                  .addComponent(p1Avatar)
                                                                  .addComponent(p1Country, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                                                     .addContainerGap())
                                    );
      
      p2Panel.setBackground(new java.awt.Color(255, 255, 153));
      
      p2Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      p2Name.setForeground(new java.awt.Color(102, 102, 0));
      p2Name.setText("Enter Nickname");
      
      p2Country.setBackground(new java.awt.Color(255, 255, 204));
      p2Country.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      p2Country.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      
      countryList2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      countryList2.setModel(new javax.swing.AbstractListModel() {
         String[] strings = alphabeticalCountries;
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      p2Country.setViewportView(countryList2);
      
      p2Avatar.setBackground(new java.awt.Color(255, 255, 204));
      p2Avatar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      
      avatarList2.setModel(new javax.swing.AbstractListModel() {
         Avatar[] strings = avatars;
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      p2Avatar.setViewportView(avatarList2);
      avatarList2.setVisibleRowCount( 3 );
      avatarList2.setLayoutOrientation( javax.swing.JList.HORIZONTAL_WRAP );
      
      javax.swing.GroupLayout p2PanelLayout = new javax.swing.GroupLayout(p2Panel);
      p2Panel.setLayout(p2PanelLayout);
      p2PanelLayout.setHorizontalGroup(
                                       p2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(p2PanelLayout.createSequentialGroup()
                                                       .addContainerGap()
                                                       .addComponent(p2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addGap(59, 59, 59)
                                                       .addComponent(p2Country, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                                       .addGap(18, 18, 18)
                                                       .addComponent(p2Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addContainerGap())
                                      );
      p2PanelLayout.setVerticalGroup(
                                     p2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2PanelLayout.createSequentialGroup()
                                                     .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                     .addComponent(p2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                     .addGap(74, 74, 74))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2PanelLayout.createSequentialGroup()
                                                     .addContainerGap()
                                                     .addGroup(p2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                  .addComponent(p2Avatar)
                                                                  .addComponent(p2Country, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                                                     .addContainerGap())
                                    );
      
      p3Panel.setBackground(new java.awt.Color(255, 153, 153));
      
      p3Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      p3Name.setForeground(new java.awt.Color(153, 0, 0));
      p3Name.setText("Enter Nickname");
      
      p3Country.setBackground(new java.awt.Color(255, 204, 204));
      p3Country.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      p3Country.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      
      countryList3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      countryList3.setModel(new javax.swing.AbstractListModel() {
         String[] strings = alphabeticalCountries;
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      p3Country.setViewportView(countryList3);
      
      p3Avatar.setBackground(new java.awt.Color(255, 204, 204));
      p3Avatar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      
      avatarList3.setModel(new javax.swing.AbstractListModel() {
         Avatar[] strings = avatars;
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      p3Avatar.setViewportView(avatarList3);
      avatarList3.setVisibleRowCount( 3 );
      avatarList3.setLayoutOrientation( javax.swing.JList.HORIZONTAL_WRAP );
      
      javax.swing.GroupLayout p3PanelLayout = new javax.swing.GroupLayout(p3Panel);
      p3Panel.setLayout(p3PanelLayout);
      p3PanelLayout.setHorizontalGroup(
                                       p3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(p3PanelLayout.createSequentialGroup()
                                                       .addContainerGap()
                                                       .addComponent(p3Name, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addGap(53, 53, 53)
                                                       .addComponent(p3Country, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                                       .addGap(18, 18, 18)
                                                       .addComponent(p3Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addContainerGap())
                                      );
      p3PanelLayout.setVerticalGroup(
                                     p3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3PanelLayout.createSequentialGroup()
                                                     .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                     .addComponent(p3Name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                     .addGap(71, 71, 71))
                                        .addGroup(p3PanelLayout.createSequentialGroup()
                                                     .addContainerGap()
                                                     .addGroup(p3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                  .addComponent(p3Avatar)
                                                                  .addComponent(p3Country, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                                     .addContainerGap())
                                    );
      
      p4Panel.setBackground(new java.awt.Color(153, 153, 255));
      
      p4Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      p4Name.setForeground(new java.awt.Color(102, 0, 153));
      p4Name.setText("Enter Nickname");
      
      p4Country.setBackground(new java.awt.Color(204, 204, 255));
      p4Country.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      p4Country.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      
      countryList4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      countryList4.setModel(new javax.swing.AbstractListModel() {
         String[] strings = alphabeticalCountries;
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      p4Country.setViewportView(countryList4);
      
      p4Avatar.setBackground(new java.awt.Color(204, 204, 255));
      p4Avatar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      
      avatarList4.setModel(new javax.swing.AbstractListModel() {
         Avatar[] strings = avatars;
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      p4Avatar.setViewportView(avatarList4);
      avatarList4.setVisibleRowCount( 3 );
      avatarList4.setLayoutOrientation( javax.swing.JList.HORIZONTAL_WRAP );
      
      javax.swing.GroupLayout p4PanelLayout = new javax.swing.GroupLayout(p4Panel);
      p4Panel.setLayout(p4PanelLayout);
      p4PanelLayout.setHorizontalGroup(
                                       p4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(p4PanelLayout.createSequentialGroup()
                                                       .addContainerGap()
                                                       .addComponent(p4Name, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                                       .addComponent(p4Country, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addGap(18, 18, 18)
                                                       .addComponent(p4Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addContainerGap())
                                      );
      p4PanelLayout.setVerticalGroup(
                                     p4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(p4PanelLayout.createSequentialGroup()
                                                     .addGap(72, 72, 72)
                                                     .addComponent(p4Name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                     .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p4PanelLayout.createSequentialGroup()
                                                     .addContainerGap()
                                                     .addGroup(p4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                  .addComponent(p4Avatar)
                                                                  .addComponent(p4Country, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                                     .addContainerGap())
                                    );
      
      oneCheck.setBackground(new java.awt.Color(0, 204, 51));
      oneCheck.setFont(new java.awt.Font("Gisha", 0, 18)); // NOI18N
      oneCheck.setText("P1");
      oneCheck.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            oneCheckActionPerformed(evt);
         }
      });
      
      twoCheck.setBackground(new java.awt.Color(255, 255, 51));
      twoCheck.setFont(new java.awt.Font("Gisha", 0, 18)); // NOI18N
      twoCheck.setText("P2");
      twoCheck.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            twoCheckActionPerformed(evt);
         }
      });
      
      threeCheck.setBackground(new java.awt.Color(255, 51, 0));
      threeCheck.setFont(new java.awt.Font("Gisha", 0, 18)); // NOI18N
      threeCheck.setText("P3");
      threeCheck.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            threeCheckActionPerformed(evt);
         }
      });
      
      fourCheck.setBackground(new java.awt.Color(102, 102, 255));
      fourCheck.setFont(new java.awt.Font("Gisha", 0, 18)); // NOI18N
      fourCheck.setText("P4");
      fourCheck.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            fourCheckActionPerformed(evt);
         }
      });
      
      back.setBackground(new java.awt.Color(255, 255, 255));
      back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      back.setForeground(new java.awt.Color(204, 0, 0));
      back.setText("Back");
      back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
      back.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
      back.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            backActionPerformed(evt);
         }
      });
      
      start.setBackground(new java.awt.Color(255, 255, 255));
      start.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      start.setForeground(new java.awt.Color(0, 153, 102));
      start.setText("Start");
      start.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
      start.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
      start.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            startActionPerformed(evt);
         }
      });
      
      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                             .addComponent(threeCheck)
                                                             .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                          .addGroup(layout.createSequentialGroup()
                                                                                       .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                       .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addComponent(twoCheck)
                                                                                                    .addComponent(fourCheck)
                                                                                                    .addComponent(oneCheck))
                                                                                       .addGap(198, 198, 198)
                                                                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addComponent(p4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                    .addComponent(p2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                    .addComponent(p1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                    .addComponent(p3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addContainerGap(837, Short.MAX_VALUE))
                               );
      layout.setVerticalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                           .addGroup(layout.createSequentialGroup()
                                                                        .addGap(70, 70, 70)
                                                                        .addComponent(p1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                           .addGroup(layout.createSequentialGroup()
                                                                        .addGap(27, 27, 27)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(81, 81, 81)
                                                                        .addComponent(oneCheck)))
                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                           .addGroup(layout.createSequentialGroup()
                                                                        .addGap(90, 90, 90)
                                                                        .addComponent(twoCheck)
                                                                        .addGap(169, 169, 169)
                                                                        .addComponent(threeCheck)
                                                                        .addGap(162, 162, 162)
                                                                        .addComponent(fourCheck))
                                                           .addGroup(layout.createSequentialGroup()
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(p2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(13, 13, 13)
                                                                        .addComponent(p3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(11, 11, 11)
                                                                        .addComponent(p4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                           .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                           .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                              .addGap(27, 27, 27))
                             );
   }// </editor-fold>    
   
   public void toggle( javax.swing.JRadioButton r, javax.swing.JPanel p ) {
      if( r.isSelected() == true ) {
         p.setVisible(true);
      }
      else
         p.setVisible(false);
   }
   
   private void oneCheckActionPerformed(java.awt.event.ActionEvent evt) {                                         
      // TODO add your handling code here:
      toggle( oneCheck, p1Panel );
      numberOfPlayers = 1;
   }                                        
   
   private void twoCheckActionPerformed(java.awt.event.ActionEvent evt) {                                         
      // TODO add your handling code here:
      toggle( twoCheck, p2Panel );
      if( oneCheck.isSelected() == false ) {
         p2Panel.setVisible(false);
      }
      
      if( p2Panel.isVisible() ) {
         numberOfPlayers = 2;
      }
   }                                        
   
   private void threeCheckActionPerformed(java.awt.event.ActionEvent evt) {                                           
      // TODO add your handling code here:
      toggle( threeCheck, p3Panel );
      if( twoCheck.isSelected() == false ) {
         p3Panel.setVisible(false);
      }
      
      if( p3Panel.isVisible() ) {
         numberOfPlayers = 3;
      }
   }                                          
   
   private void fourCheckActionPerformed(java.awt.event.ActionEvent evt) {                                          
      // TODO add your handling code here:
      toggle( fourCheck, p4Panel );
      if( threeCheck.isSelected() == false ) {
         p4Panel.setVisible(false);
      }
      
      if( p4Panel.isVisible() ) {
         numberOfPlayers = 4;
      }
   }                                         
   
   private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     
      // TODO add your handling code here:
      setVisible( false );
      app.mainMenu.setVisible( true );
      
   }
   
   private void startActionPerformed(java.awt.event.ActionEvent evt) {                                      
      // TODO add your handling code here:
      String[] namesOfPlayers;
      int[] locationsOfPlayers;
      Avatar[] avatarsOfPlayers;
      String country;
      
      namesOfPlayers = new String[ numberOfPlayers ];
      locationsOfPlayers = new int[ numberOfPlayers ];
      avatarsOfPlayers = new Avatar[ numberOfPlayers ];
      for ( int n = 0; n < numberOfPlayers; n++ )
      {
         namesOfPlayers[ n ] = getPlayerName( n );
         locationsOfPlayers[ n ] = getSelectedCountry( n );
         avatarsOfPlayers[ n ] = getSelectedAvatar( n );
      }
      
      app.gameGui = new GameGUI( app, new Game( numberOfPlayers, locationsOfPlayers, namesOfPlayers, avatarsOfPlayers ) ); 
      app.add( app.gameGui );
      setVisible( false );
   }                                     
   
   public String getPlayerName( int playerNo ) {
      if( playerNo == 0 ) {
         return p1Name.getText();
      }
      
      else if( playerNo == 1 ) {
         return p2Name.getText();
      }
      
      else if( playerNo == 2 ) {
         return p3Name.getText();
      }
      
      else
         return p4Name.getText();
   }
   
   public int getSelectedCountry( int playerNo ) {
      if( playerNo == 0 ) {
         return listedCountries.indexOf( countryList1.getSelectedValue().toString() );
      }
      
      else if( playerNo == 1 ) {
         return listedCountries.indexOf( countryList2.getSelectedValue().toString() );
      }
      
      else if( playerNo == 2 ) {
         return listedCountries.indexOf( countryList3.getSelectedValue().toString() );
      }
      
      else
         return listedCountries.indexOf( countryList4.getSelectedValue().toString() );
   }
   
   public Avatar getSelectedAvatar( int playerNo )
   {
      if( playerNo == 0 ) {
         return (Avatar)avatarList1.getSelectedValue();
      }
      
      else if( playerNo == 1 ) {
         return (Avatar)avatarList2.getSelectedValue();
      }
      
      else if( playerNo == 2 ) {
         return (Avatar)avatarList3.getSelectedValue();
      }
      
      else
         return (Avatar)avatarList4.getSelectedValue();
   }
   
   
   
   
   // Variables declaration - do not modify                     
   private javax.swing.JList avatarList1;
   private javax.swing.JList avatarList2;
   private javax.swing.JList avatarList3;
   private javax.swing.JList avatarList4;
   private javax.swing.JButton back;
   private javax.swing.JList countryList1;
   private javax.swing.JList countryList2;
   private javax.swing.JList countryList3;
   private javax.swing.JList countryList4;
   private javax.swing.JRadioButton fourCheck;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JTextField p3Name;
   private javax.swing.JTextField p4Name;
   private javax.swing.JRadioButton oneCheck;
   private javax.swing.JScrollPane p1Avatar;
   private javax.swing.JScrollPane p1Country;
   private javax.swing.JTextField p1Name;
   private javax.swing.JPanel p1Panel;
   private javax.swing.JScrollPane p2Avatar;
   private javax.swing.JScrollPane p2Country;
   private javax.swing.JTextField p2Name;
   private javax.swing.JPanel p2Panel;
   private javax.swing.JScrollPane p3Avatar;
   private javax.swing.JScrollPane p3Country;
   private javax.swing.JPanel p3Panel;
   private javax.swing.JScrollPane p4Avatar;
   private javax.swing.JScrollPane p4Country;
   private javax.swing.JPanel p4Panel;
   private javax.swing.JButton start;
   private javax.swing.JRadioButton threeCheck;
   private javax.swing.JRadioButton twoCheck;
   // End of variables declaration                   
}
