package gui;

import java.awt.*;  
import java.awt.event.*;
import javax.swing.*;
import mainCode.*;
import java.util.ArrayList;
import java.util.Observer;
import java.util.Observable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kaan.uguralp-ug
 */
public class QuestionPage extends javax.swing.JPanel implements Observer {
    
    /**
     * Creates new form QuestionPageJ
     */
    
    GameGUI parent;
    Timer timer;
    ArrayList<JButton> choiceButtons;
    public static final int CHOICE_NUMBER = 3;
    public static final int ONE_SECOND = 1000;
    public static final int QUESTION_TIME = 15;
    int remainingTime;  
    Game game;
    int n;
    
    public QuestionPage( GameGUI parent ) {
        initComponents();
        
        this.parent = parent;
        game = parent.game;
        
        choiceButtons = new ArrayList<JButton>();
        choiceButtons.add( choiceOne );
        choiceButtons.add( choiceTwo );
        choiceButtons.add( choiceThree );
        
        game.getQuiz().addObserver( this );
        
        handleActionListeners();
        
        timer = new Timer(ONE_SECOND, new QuestionTimeListener() );
        
        setVisible( false );
    }
    
    public void handleActionListeners()
    {
        for ( n = 0; n < CHOICE_NUMBER; n++ )
        {
            choiceButtons.get( n ).addActionListener( new ChoiceBtnListener() );
        }
    }
    
    public class QuestionTimeListener implements ActionListener
    {
        @Override
        public void actionPerformed( ActionEvent evt )
        {
            remainingTime--;
            
            timeLabel.setText( remainingTime + "" );
            
            if ( remainingTime == 0 ) 
            {
                timer.stop();
                
                game.youLose();
            }
        }
    }
    
    public class ChoiceBtnListener implements ActionListener
    {
        @Override
        public void actionPerformed( ActionEvent evt )
        {                  
            timer.stop();
            
            game.giveAnswerToQuestion( choiceButtons.indexOf( evt.getSource() ) );
        }
    }
    
    public void update( Observable obs, Object obj )
    {      
        Quiz quiz = (Quiz)obs;
        Question currentQuestion = quiz.getQuestion();
        
        if ( quiz.isQuizzing() )
        {
            remainingTime = QUESTION_TIME;
            
            timeLabel.setText( remainingTime + "" );      
            header.setText( "QUESTION   " + ( quiz.getQuestionNumber() + 1 ) );
            questionSentence.setText( currentQuestion.getQuestionSentence() );
            for ( n = 0; n < CHOICE_NUMBER; n++ )
            {
                choiceButtons.get( n ).setText( currentQuestion.getChoice( n ) );
            }
            
            timer.start();
            setVisible( true );
        }
        else
        {
            setVisible( false );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

        choiceOne = new javax.swing.JButton();
        choiceTwo = new javax.swing.JButton();
        choiceThree = new javax.swing.JButton();
        header = new javax.swing.JLabel();
        questionSentence = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 255));

        choiceOne.setBackground(new java.awt.Color(204, 255, 255));
        choiceOne.setFont(new java.awt.Font("Gisha", 0, 14)); // NOI18N
        choiceOne.setText("1");
        choiceOne.setToolTipText("");

        choiceTwo.setBackground(new java.awt.Color(204, 255, 255));
        choiceTwo.setFont(new java.awt.Font("Gisha", 0, 14)); // NOI18N
        choiceTwo.setText("2");

        choiceThree.setBackground(new java.awt.Color(204, 255, 255));
        choiceThree.setFont(new java.awt.Font("Gisha", 0, 14)); // NOI18N
        choiceThree.setText("3");

        header.setFont(new java.awt.Font("Gisha", 0, 18)); // NOI18N
        header.setForeground(new java.awt.Color(0, 0, 204));
        header.setText("jLabel1");

        questionSentence.setBackground(new java.awt.Color(255, 255, 255));
        questionSentence.setFont(new java.awt.Font("Gisha", 0, 18)); // NOI18N
        questionSentence.setText("jLabel1");

        timeLabel.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(0, 102, 102));
        timeLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(questionSentence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(choiceOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choiceTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choiceThree, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionSentence, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(choiceOne, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceThree, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton choiceFour;
    private javax.swing.JButton choiceOne;
    private javax.swing.JButton choiceThree;
    private javax.swing.JButton choiceTwo;
    private javax.swing.JLabel header;
    private javax.swing.JLabel questionSentence;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration                   
}
